name: Tests

on:                                             
  - pull_request
  - push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11.7', '3.12.0']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: pip install tox
      
    # If your project requires additional dependencies before running tox, install them here
    - name: Install project dependencies
      run: pip install -r requirements.txt tox tox-gh-actions
      
    # Run the tox command
    - name: Test with tox
      run: tox
